manager/urls.py
from django.urls import path
from manager import views

app_name = 'manager'

urlpatterns = [
    path('document_parking_list/', views.document_parking_list, name='document_parking_list'),
    path('document_car_list=<int:id_parking>/', views.document_car_list, name='document_car_list'),
    path('document_all_car_list/', views.document_all_car_list, name='document_all_car_list'),
]

parking_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from manager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.empty_path, name='index'),
    path('login/', views.login_page, name='login_page'),
    path('login_check/', views.login_check, name='login_check'),
    path('logout/', views.logout, name='logout'),
    path('main/', views.main_page, name='main_page'),
    path('define_parking_manager_page/', views.define_parking_manager_page, name='define_parking_manager_page'),
    path('employee_list/', views.employees_list_page, name='employees_list_page'),
    path('employee/', views.employee_page, name='employee_page'),
    path('employee=<int:id_employee>/', views.employee_page, name='employee_page'),
    path('employee_create/', views.employee_create, name='employee_create'),
    path('employee_update=<int:id_employee>/', views.employee_create, name='employee_update'),
    path('employee_delete=<int:id_employee>/', views.employee_delete, name='employee_delete'),
    path('parking_list/', views.parking_list_page, name='parking_list_page'),
    path('parking_page/', views.parking_page, name='parking_page'),
    path('parking_page=<int:id_parking>/', views.parking_page, name='parking_page'),
    path('parking_create/', views.parking_create, name='parking_create'),
    path('parking_update=<int:id_parking>/', views.parking_create, name='parking_update'),
    path('parking_delete=<int:id_parking>/', views.parking_delete, name='parking_delete'),
    path('car_list_page=<int:id_parking>/', views.car_list_page, name='car_list_page'),
    path('have_not_parking/', views.have_not_parking_page, name='have_not_parking_page'),
    path('car_page_parking=<int:id_parking>/', views.car_page, name='car_page'),
    path('car_page=<int:id_car>/', views.car_page, name='car_page'),
    path('car_create_parking=<int:id_parking>/', views.car_create, name='car_create'),
    path('car_update=<int:id_car>/', views.car_create, name='car_update'),
    path('car_delete=<int:id_car>/', views.car_delete, name='car_delete'),
    path('car_search/', views.car_search_page, name='car_search_page'),
    path('documents/', include('manager.urls')),
]

manager/models.py
from django.db import models


class Employee(models.Model):
    positionChoices = (
        ('a', 'Администратор',),
        ('s', 'Секретарь',),
        ('p', 'Управляющий стоянкой',),
    )

    id_employee = models.SmallAutoField(primary_key=True)
    surname = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    patronymic = models.CharField(max_length=20, blank=True, default='')
    position = models.CharField(max_length=1, choices=positionChoices)
    phone = models.CharField(max_length=11)
    password = models.CharField(unique=True, max_length=12)


    class Meta:
        db_table = 'employee'


class CarParking(models.Model):
    id_number = models.SmallAutoField(primary_key=True)
    id_employee = models.OneToOneField('Employee', models.RESTRICT, db_column='id_employee')
    parking_number = models.PositiveSmallIntegerField(unique=True)
    title = models.CharField(unique=True, max_length=20)
    district = models.CharField(max_length=20)
    street = models.CharField(max_length=20)

    class Meta:
        db_table = 'car_parking'


class CarBrand(models.Model):
    id_brand = models.SmallAutoField(primary_key=True)
    brand = models.CharField(max_length=20)

    class Meta:
        db_table = 'car_brand'


class CarModel(models.Model):
    id_model = models.SmallAutoField(primary_key=True)
    id_brand = models.ForeignKey('CarBrand', models.CASCADE, db_column='id_brand')
    model = models.CharField(max_length=20)

    class Meta:
        db_table = 'car_model'


class Car(models.Model):
    id_car_number = models.AutoField(primary_key=True)
    gov_car_number = models.CharField(unique=True, max_length=9)
    id_number = models.ForeignKey('CarParking', models.RESTRICT, db_column='id_number')
    id_model = models.ForeignKey('CarModel', models.RESTRICT, db_column='id_model')
    color = models.PositiveSmallIntegerField()
    mileage = models.PositiveIntegerField()
    owner_name = models.CharField(max_length=20)
    owner_surname = models.CharField(max_length=20)
    owner_patronymic = models.CharField(max_length=20, blank=True, default='')
    phone = models.CharField(max_length=11)

    class Meta:
        db_table = 'car'

manager/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, FileResponse
from django.urls import reverse
from manager.data.menu import MenuClass
from manager.data import employee, parking, car, documents
from manager.data.login import Login, is_login, restriction_check


def empty_path(request):
    return HttpResponseRedirect(reverse('login_page'))


@is_login
def login_page(request):
    context = _create_context(request.session)
    _show_error_message(request.session, context)
    return render(request, 'manager/login.html', context)


@is_login
def login_check(request) -> HttpResponseRedirect:
    password = request.POST['password_field']
    next_url = 'main_page'
    loginCheck = Login(password)
    if loginCheck.is_login_correct():
        employeeLoginId = loginCheck.get_login_id()
        SessionStorageEmployee.add_employee_data_in_session(
            request.session, employeeLoginId)
    else:
        next_url = 'login_page'
        _add_error_message(request.session, loginCheck.get_msg())
    return HttpResponseRedirect(reverse(next_url))


def logout(request) -> HttpResponseRedirect:
    SessionStorageEmployee.delete_employee_data_in_session(request.session)
    return HttpResponseRedirect(reverse('login_page'))


@restriction_check(employee.Employee.PARKING_MANAGER)
def main_page(request):
    context = _create_context(request.session, 1)
    SessionStorageEmployee.add_hello_label(request.session, context)
    return render(request, 'manager/main.html', context)


@restriction_check(employee.Employee.ADMIN, employee.Employee.SECRETARY)
def define_parking_manager_page(request):
    parkingManagerId = SessionStorageEmployee.get_id(request.session)
    parkingId = parking.Parking.get_parking_id_attached_parking_manager(parkingManagerId)
    if parkingId > -1:
        redirectUrl = reverse('car_list_page', kwargs={'id_parking': parkingId})
    else:
        redirectUrl = reverse('have_not_parking_page')
    return HttpResponseRedirect(redirectUrl)


@restriction_check(employee.Employee.SECRETARY, employee.Employee.PARKING_MANAGER)
def employees_list_page(request):
    context = _create_context(request.session)
    el = employee.EmployeesList()
    context['employees_list'] = el.get_list()
    context['employees_count'] = el.get_size()
    _show_error_message(request.session, context)
    return render(request, 'manager/employees_list.html', context)


@restriction_check(employee.Employee.SECRETARY, employee.Employee.PARKING_MANAGER)
def employee_page(request, id_employee: int = -1):
    context = _create_context(request.session)
    context['positions'] = employee.Employee.get_position_choices()

    if id_employee > -1:
        context['id_employee'] = id_employee
        context['title'] = 'Изменение информации о сотруднике'
        context['password'] = 'Изменение пароля'
        context['button'] = 'Сохранить'
        # отключить поле выбора должности, если администратор изменяет себя
        adminId = SessionStorageEmployee.get_id(request.session)
        if id_employee == adminId:
            context['positionDisabled'] = True
        if not 'employee_page' in request.session:
            context.update(employee.Employee.get_employee_values(id_employee))
    else:
        context['title'] = 'Добавление нового сотрудника'
        context['password'] = 'Пароль'
        context['button'] = 'Создать'
        context['employee_position'] = 's'

    if 'employee_page' in request.session:
        context.update(request.session['employee_page'])
        del request.session['employee_page']
    _show_error_message(request.session, context)

    return render(request, 'manager/employee.html', context)


@restriction_check(employee.Employee.SECRETARY, employee.Employee.PARKING_MANAGER)
def employee_create(request, id_employee: int=-1) -> HttpResponseRedirect:
    ''' Создание/обновление сотрудника '''
    if id_employee > -1:
        adminId = SessionStorageEmployee.get_id(request.session)
        e = employee.EmployeeUpdate(request.POST, id_employee, adminId)
    else:
        e = employee.EmployeeAddNew(request.POST)

    urlDict = dict()
    if e.get_status():
        nextUrl = 'employee_page' if 'go_next' in request.POST else 'employees_list_page'
    else:
        nextUrl = 'employee_page'
        request.session['employee_page'] = e.get_employee_data()
        _add_error_message(request.session, e.get_msg())
        if id_employee > -1:
            urlDict['id_employee'] = id_employee
    return HttpResponseRedirect(reverse(nextUrl, kwargs=urlDict))


@restriction_check(employee.Employee.SECRETARY, employee.Employee.PARKING_MANAGER)
def employee_delete(request, id_employee: int) -> HttpResponseRedirect:
    adminId = SessionStorageEmployee.get_id(request.session)
    e = employee.EmployeeDelete(id_employee, adminId)
    if not e.get_status():
        _add_error_message(request.session, e.get_msg())
    return HttpResponseRedirect(reverse('employees_list_page'))


@restriction_check(employee.Employee.PARKING_MANAGER)
def parking_list_page(request):
    context = _create_context(request.session)
    el = parking.ParkingList()
    context['parking_list'] = el.get_list()
    context['parking_count'] = el.get_size()
    _show_error_message(request.session, context)
    return render(request, 'manager/parking_list.html', context)


@restriction_check(employee.Employee.PARKING_MANAGER)
def parking_page(request, id_parking: int = -1):
    context = _create_context(request.session)

    if id_parking > -1:
        context['id_parking'] = id_parking
        context['title'] = 'Изменение информации о стоянке'
        context['button'] = 'Сохранить'
        managers = employee.ManagersList()
        context['employees'] = managers.get_list()
        if not 'parking_page' in request.session:
            context.update(parking.Parking.get_parking_values(id_parking))
    else:
        context['title'] = 'Добавление новой стоянки'
        context['button'] = 'Создать'
        if _add_manager_list(request, context) == 0:
            return HttpResponseRedirect(reverse('parking_list_page'))

    if 'parking_page' in request.session:
        context.update(request.session['parking_page'])
        del request.session['parking_page']
    _show_error_message(request.session, context)
    return render(request, 'manager/parking.html', context)


def _add_manager_list(request, context) -> int:
    managers = employee.ManagersList(freeManagers=True)
    context['employees'] = managers.get_list()
    if not managers.get_status():
        _add_error_message(request.session, managers.get_msg())
    return managers.get_size()


@restriction_check(employee.Employee.PARKING_MANAGER)
def parking_create(request, id_parking: int=-1) -> HttpResponseRedirect:
    ''' Создание/обновление стоянки '''
    if id_parking > -1:
        p = parking.ParkingUpdate(request.POST, id_parking)
    else:
        p = parking.ParkingAddNew(request.POST)

    urlDict = dict()
    if p.get_status():
        nextUrl = 'parking_page' if 'go_next' in request.POST else 'parking_list_page'
    else:
        nextUrl = 'parking_page'
        request.session['parking_page'] = p.get_parking_data()
        _add_error_message(request.session, p.get_msg())
        if id_parking > -1:
            urlDict['id_parking'] = id_parking
    return HttpResponseRedirect(reverse(nextUrl, kwargs=urlDict))


@restriction_check(employee.Employee.PARKING_MANAGER)
def parking_delete(request, id_parking: int) -> HttpResponseRedirect:
    p = parking.ParkingDelete(id_parking)
    if not p.get_status():
        _add_error_message(request.session, p.get_msg())
    return HttpResponseRedirect(reverse('parking_list_page'))


@restriction_check()
def car_list_page(request, id_parking: int):
    employeePosition = SessionStorageEmployee.get_position(request.session)
    openedMenuItem = 1 if employeePosition == employee.Employee.PARKING_MANAGER else -1
    context = _create_context(request.session, openedMenuItem)
    SessionStorageEmployee.add_hello_label(request.session, context)
    cl = car.CarList(id_parking)
    context['car_list'] = cl.get_list()
    context['cars_count'] = cl.get_size()
    context['parking_id'] = id_parking
    context['parking'] = parking.Parking.get_parking_values(id_parking)
    _show_error_message(request.session, context)
    return render(request, 'manager/car_list.html', context)


@restriction_check(employee.Employee.ADMIN, employee.Employee.SECRETARY)
def have_not_parking_page(request):
    context = _create_context(request.session, 1)
    return render(request, 'manager/have_not_parking.html', context)


@restriction_check()
def car_page(request, id_parking: int=-1, id_car: int = -1):
    context = _create_context(request.session)
    context['color_list'] = car.Car.CAR_COLOURS
    context['brand_dict'] = car.Car.get_car_brands()

    if id_car > -1:
        context['id_car'] = id_car
        context['title'] = 'Изменение информации об автомобиле'
        context['button'] = 'Сохранить'
        idEmployee = SessionStorageEmployee.get_id(request.session)
        employeePosition = SessionStorageEmployee.get_position(request.session)
        context['parking_list'] = parking.ParkingList.get_list_for_car(employeePosition, idEmployee)
        if not 'car_page' in request.session:
            context.update(car.Car.get_car_values(id_car))
    else:
        context['title'] = 'Добавление нового автомобиля'
        context['button'] = 'Создать'
        context['parking'] = parking.Parking.get_parking_values(id_parking)
        context['id_parking'] = id_parking

    if 'car_page' in request.session:
        context.update(request.session['car_page'])
        del request.session['car_page']
    _show_error_message(request.session, context)
    return render(request, 'manager/car.html', context)


@restriction_check()
def car_create(request, id_parking: int=-1, id_car: int=-1) -> HttpResponseRedirect:

manager/templates/manager/base.html
<!-- Основной шаблон -->
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Проект по Базам данных</title>
  <link rel="stylesheet" type="text/css" href="{% static 'manager/styles/site_base.css' %}" />
  {% block extrastylesmenu %}{% endblock %}
  {% block extrastyles %}{% endblock %}
</head>

<body>
  {% block menu %}{% endblock %}
  <div id='site_content'>
    {% block content %}
    Hello, world. You're at the manager app index.<br>
    <!-- Заглушка генерирующая текст -->
    {% lorem 3 p %}
    {% endblock %}
  </div>
</body>
</html>

manager/templates/manager/car.html
<!-- Страница добавления/редактирования автомобиля -->
{% extends "manager/menu.html" %}
{% load static %}

{% block extrastyles %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/form_create_update.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/car_create_update.css' %}" />
{% endblock %}

{% block content %}
{% if not id_car %}
<a href="{% url 'car_list_page' id_parking=id_parking %}">
{% else %}
<a href="{% url 'car_list_page' id_parking=car_id_number %}">
{% endif %} <p id='back_links'>← Назад на страницу стоянки</p>
</a>
<h1>{{ title }}</h1>
{% if parking %}
<p>На стоянку №{{ parking.parking_parking_number }} "{{ parking.parking_title }}":</p>
{% endif %}
{% if error_msg %} <p class="err_msg">{{ error_msg }}</p> {% endif %}
<form {% if not id_car %}
  action="{% url 'car_create' id_parking=id_parking %}"
  {% else %}
  action="{% url 'car_update' id_car=id_car %}"
  {% endif %} method="post">
  {% csrf_token %}
  Государственный номер: <input type="text" name="gov_car_number_field" maxlength="9"
  {% if car_gov_car_number %}
    value = "{{car_gov_car_number}}"
  {% endif %}><br>

  {% if parking_list %}
  <div>
    Стоянка:<select name="parking_field"
    {% if employee_position == 'p' %}
    disabled
    {% endif %}>
      {% for id, title in parking_list.items %}
        <option value="{{ id }}"
        {% if id == car_id_number %}
          selected="selected"
        {% endif %}>{{ title }}</option>
      {% endfor %}
    </select>
  </div>
  {% endif %}

  <input type="radio" name="new_model_radio" id="old_model" value="0"
  {% if not new_model_radio or new_model_radio == "0" %}
    checked="checked"
  {% endif %}/>
  <label for="old_model">Выбрать модель из списка</label><br>
  <div class="old_model">
  Марка и модель:<select name="id_model_field">
    {% for model in brand_dict.1 %}
      <option value="{{model.0}}"
      {% if model.0 == car_id_model %}
        selected="selected"
      {% endif %}>{{model.1}}</option>
    {% endfor %}
  </select>
  </div>

  <input type="radio" name="new_model_radio" id="new_model" value="1"
  {% if new_model_radio == "1" %}
    checked="checked"
  {% endif %}/>
  <label for="new_model">Добавить новую модель</label><br>
  <div class="new_model">
    Марка:<select name="1_brand_field">
      {% for brand in brand_dict.0 %}
        <option value="{{brand.0}}"
        {% if brand.0 == car_brand_int %}
          selected="selected"
        {% endif %}>{{brand.1}}</option>
      {% endfor %}
    </select><br>

    Новая модель:<input type="text" name="1_model_field"
    {% if car_model_str %}
      value = "{{car_model_str}}"
    {% endif %}>
  </div>

  <input type="radio" name="new_model_radio" id="new_brand" value="2"
  {% if new_model_radio == "2" %}
    checked="checked"
  {% endif %}/>
  <label for="new_brand">Добавить новую марку и модель</label><br>
  <div class="new_brand">
    Новая марка:<input type="text" name="2_brand_field"
    {% if car_brand_str %}
      value = "{{car_brand_str}}"
    {% endif %}><br>

    Новая модель:<input type="text" name="2_model_field"
    {% if car_model_str %}
      value = "{{car_model_str}}"
    {% endif %}><br>
  </div>

  Цвет:<select name="color_field">
    {% for value, name in color_list.items %}
      <option value="{{value}}"
      {% if value == car_color %}
        selected="selected"
      {% endif %}>{{name}}</option>
    {% endfor %}
  </select><br>

  Пробег:<input type="number" name="mileage_field" min="0"
  {% if car_mileage %}
    value = "{{car_mileage}}"
  {% endif %}><br>

  Владелец автомобиля:<br>
  Имя: <input type="text" name="owner_name_field"
  {% if car_owner_name %}
    value = "{{car_owner_name}}"
  {% endif %}><br>

  Фамилия: <input type="text" name="owner_surname_field"
  {% if car_owner_surname %}
    value = "{{car_owner_surname}}"
  {% endif %}><br>

  Отчество*: <input type="text" name="owner_patronymic_field"
  {% if car_owner_patronymic %}
    value = "{{car_owner_patronymic}}"
  {% endif %}><br>

  Номер телефона: <input type="tel" name="phone_field" minlength='11' maxlength="12"
  {% if car_phone %}
    value = "{{car_phone}}"
  {% endif %}><br>

  <p>* - знак означает, что поле можно оставить пустым.</p>
  <input type="submit" value="{{ button }}" />
  {% if id_parking %}
  <input type="submit" name="go_next" value="Добавить и перейти к следующей" />
  {% endif %}
</form>
{% endblock %}

manager/templates/manager/car_list.html
<!-- Страница со списком автомобилей на стоянке -->
{% extends "manager/menu.html" %}
{% load static %}

{% block extrastyles %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/car_list.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/table.css' %}" />
{% endblock %}

{% block content %}
{% if employee_position == 'a' or employee_position == 's' %}
<a href="{% url 'main_page' %}"><p id='back_links'>← Главная страница</p></a>
<a href="{% url 'parking_list_page' %}"><p id='back_links'>/ Вернуться к списку стоянок</p></a>
{% endif %}

{% if login_success %}
<p id="hello">Добро пожаловать {{ employee_surname_name }}!</p>
{% endif %}

<h1>Страница стоянки №{{ parking.parking_parking_number }} "{{ parking.parking_title }}"</h1>
<p>Адрес: {{ parking.parking_district }} район, улица {{ parking.parking_street }}.</p>
<h2>Список автомобилей на стоянке</h2>
{% if error_msg %} <p class="err_msg">{{ error_msg }}</p> {% endif %}
<p id="field_count">Количество автомобилей: {{ cars_count }}</p>
<a href="{% url 'car_page' id_parking=parking_id %}">
  <p id='button_table'>Добавить автомобиль</p></a>
<a href="{% url 'manager:document_car_list' id_parking=parking_id %}" target="_blank">
  <p id='button_table'>Получить документ со списком автомобилей</p></a>
{% if cars_count > 0 %}
<div id='table'>
  <table>
    <tr>
      <th>Государственный<br>номер</th>
      <th>Марка</th>
      <th>Модель</th>
      <th>Цвет</th>
      <th>Пробег</th>
      <th>Владелец</th>
      <th>Телефон</th>
    </tr>
    {% for c in car_list %}
    <tr>
      <td>{{c.1}}</td>
      <td>{{c.2}}</td>
      <td>{{c.3}}</td>
      <td>{{c.4}}</td>
      <td>{{c.5}}</td>
      <td>{{c.6}}</td>
      <td>{{c.7}}</td>
      <td><a href="{% url 'car_page' id_car=c.0 %}"><p id='button_table'>Изменить</p></a></td>
      <td><a href="{% url 'car_delete' id_car=c.0 %}"><p id='button_table'>Удалить</p></a></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% else %}
<div>
  <p>На стоянке нет зарегистрированных автомобилей. Добавьте их.</p>
</div>
{% endif %}
{% endblock %}

manager/templates/manager/car_list_search.html
<!-- Страница с поиском автомобилей -->
{% extends "manager/menu.html" %}
{% load static %}

{% block extrastyles %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/car_list.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/table.css' %}" />
{% endblock %}

{% block content %}
<a href="{% url 'main_page' %}">
  <p id='back_links'>← Главная страница</p>
</a>
<h1>Поиск автомобиля по государственному номеру</h1>
{% if error_msg %} <p class="err_msg">{{ error_msg }}</p> {% endif %}
<form action="{% url 'car_search_page' %}" method="get">

  Введите государственный номер: <input type="text" name="search_field" maxlength="9"
  {% if car_search %}
    value = "{{car_search}}"
  {% endif %}>

  <input type="submit" value="Найти" />
</form>
{% if status_ok %}
  {% if cars_count > 0 %}
    <p id="field_count">Найдено автомобилей: {{cars_count}}.</p>
    <div id='table'>
      <table>
        <tr>
          <th>Государственный<br>номер</th>
          <th>Марка</th>
          <th>Модель</th>
          <th>Цвет</th>
          <th>Пробег</th>
          <th>Владелец</th>
          <th>Телефон</th>
          <th>Стоянка</th>
        </tr>
        {% for c in car_list %}
          <tr>
            <td>{{c.1}}</td>
            <td>{{c.2}}</td>
            <td>{{c.3}}</td>
            <td>{{c.4}}</td>
            <td>{{c.5}}</td>
            <td>{{c.6}}</td>
            <td>{{c.7}}</td>
            <td>{{c.8}}</td>
            <td><a href="{% url 'car_page' id_car=c.0 %}"><p id='button_table'>Изменить</p></a></td>
            <td><a href="{% url 'car_delete' id_car=c.0 %}"><p id='button_table'>Удалить</p></a></td>
          </tr>
        {% endfor %}
      </table>
    </div>
  {% else %}
    <div>
      <p>Автомобили с указанным номером не найдены.</p>
    </div>
  {% endif %}
{% else %}
  <div>
    <p>Введите государственный номер для поиска.</p>
  </div>
{% endif %}
{% endblock %}

manager/templates/manager/main.html
<!-- Главная страница в приложении -->
{% extends "manager/menu.html" %}
{% load static %}

{% block extrastyles %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/main_page.css' %}" />
{% endblock %}

{% block content %}
<h1>Главная страница</h1>
{% if login_success %}
<p id="hello">Добро пожаловать {{ employee_surname_name }}!</p>
{% endif %}
<div id="main_menu">
  {% if employee_position == 'a' %}
  <div class="main_item">
    <a href="{% url 'employees_list_page' %}">
    <p>Список сотрудников</p>
    <img src="{% static 'images/employees.jpg' %}" alt="Список сотрудников">
    </a>
  </div>
  {% endif %}
  <div class="main_item">
    <a href="{% url 'parking_list_page' %}">
    <p>Список стоянок</p>
    <img src="{% static 'images/parking_lots.jpg' %}" alt="Список стоянок">
    </a>
  </div>
  <div class="main_item">
    <a href="{% url 'car_search_page' %}">
    <p>Найти автомобиль по номеру</p>
    <img src="{% static 'images/find_car.jpg' %}" alt="Найти автомобиль">
    </a>
  </div>
  <div class="main_item">
    <a href="{% url 'manager:document_all_car_list' %}" target="_blank">
    <p>Документ с количеством автомобилей на всех стоянках</p>
    <img src="{% static 'images/document.jpg' %}" alt="Документ">
    </a>
  </div>
</div>
{% endblock %}

manager/templates/manager/parking_list.html
<!-- Страница со списком стоянок -->
{% extends "manager/menu.html" %}
{% load static %}

{% block extrastyles %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/parking_list.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'manager/styles/table.css' %}" />
{% endblock %}

{% block content %}
<a href="{% url 'main_page' %}">
  <p id='back_links'>← Главная страница</p>
</a>
<h1>Список стоянок</h1>
{% if error_msg %} <p class="err_msg">{{ error_msg }}</p> {% endif %}
<p id="field_count">Количество стоянок: {{ parking_count }}</p>
<a href="{% url 'parking_page' %}">
  <p id='button_table'>Добавить стоянку</p></a>
<a href="{% url 'manager:document_parking_list' %}" target="_blank">
  <p id='button_table'>Получить документ со списком стоянок</p></a>
{% if parking_count > 0 %}
<div id='table'>
  <table>
    <tr>
      <th>Номер<br>стоянки</th>
      <th>Название</th>
      <th>Район</th>
      <th>Улица</th>
      <th>Управляющий</th>
      <th>Телефон</th>
    </tr>
    {% for p in parking_list %}
    <tr>
      <td>{{p.1}}</td>
      <td>{{p.2}}</td>
      <td>{{p.3}}</td>
      <td>{{p.4}}</td>
      <td>{{p.5}}</td>
      <td>{{p.6}}</td>
      <td><a href="{% url 'car_list_page' id_parking=p.0 %}"><p id='button_table'>Список автомобилей</p></a></td>
      <td><a href="{% url 'parking_page' id_parking=p.0 %}"><p id='button_table'>Изменить</p></a></td>
      <td><a href="{% url 'parking_delete' id_parking=p.0 %}"><p id='button_table'>Удалить</p></a></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% else %}
<div>
  <p>В базе данных отсутствует информация о стоянках. Добавьте их.</p>
</div>
{% endif %}
{% endblock %}